name: Train and Deploy MLflow Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r MLProject/requirements.txt
        pip install mlflow scikit-learn pandas

    - name: Run MLflow Project
      working-directory: ./MLProject
      run: |
        export MLFLOW_ARTIFACT_URI=file://$(pwd)/mlruns
        mlflow run . --env-manager=local -P data_path="namadataset_preprocessing/dataset.csv"

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns/

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      working-directory: ./MLProject
      run: |
        RUN_ID=$(ls mlruns/0 | head -n 1)
        mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/model -n ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
